### ISSUE TITLE
User has no way of submitting a new registration

### ISSUE THREAD

**Issue by quicodesfor** [cforlando/voter-registration#1]
Must be web based.

Any other requirements? @chadmiller

**Comment by quicodesfor** [comment]
Would a user need to submit the new registration electronically?
Doesn't this service print the input to paper?

**Comment by chadmiller** [comment]
There should be a submit button at the bottom, but I'll wire that up to do something, later.

**Comment by chadmiller** [comment]
For example interface, see
https://github.com/cforlando/voter-registration/wiki

**Comment by quicodesfor** [comment]
Run example or see https://serene-springs-67394.herokuapp.com/
