### ISSUE TITLE
User has no way of updating an existing registration

### ISSUE THREAD

**Issue by chadmiller** [cforlando/voter-registration#2]
Underneath the scenes, the current registration is pigeonholed by "mm-dd-yyyy" birthdate of registrant, then a trie of user data mapping to voter-ids. Then, many groups of voter-ids to voter full info. Those are details you don't care about.

The important part is that to search, pass the birth-date, and an array of the values of each input field in the form. When search is finished, the searcher will call a rendering function you provide as the third argument above, with the most likely existing registrations in an array as the only parameter.

I think the user should pick from a list to fill the form, or automatically fill the topmost and wait for refinements or something. Up to you. I'm not the UI expert.

**Comment by quicodesfor** [comment]
Run example or see https://serene-springs-67394.herokuapp.com/
